### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by viviweikuo**
姓名：郭宸瑋
http://18.213.194.28:3000/api/attractions?page=1
http://18.213.194.28:3000/api/attractions?page=0&keyword=藝文館所
http://18.213.194.28:3000/api/attractions?page=0&keyword=北
http://18.213.194.28:3000/api/attractions?page=1&keyword=北
http://18.213.194.28:3000/api/attraction/10
http://18.213.194.28:3000/api/attraction/100
http://18.213.194.28:3000/api/categories

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review explicitly so that I can review for you. Your live URLs are broken.

**Comment by viviweikuo** [comment]
@cwpeng Hi teacher,
I fixed up the links! Please review again uwu

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"
2. Based on our data, there should have something in http://18.213.194.28:3000/api/attractions?page=4
3. `"Null"` is not `null`. Use correct data for response.

Solve issues and re-request review.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
