### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by viviweikuo**
Name: 郭宸瑋
Link: http://18.213.194.28:3000/
Assignment: from week 2 to week 4 (home page, product page and membership system)

Hi teacher,
I'm sorry for the late submission.
Finally, I have finished the desired version of assignment after fixing many times.
Please check, and work of week 5 is on the way (I hope...T_T

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Password input should use input element with type password.
2. Add link to home page on website title.
3. Add some padding to date input in attraction page.
4. Aspect ratio of any images in your attraction page should keep the same as original ones in any size of devices.

**Comment by viviweikuo** [comment]
@cwpeng Hi teacher,
I fixed up the stuffs you mentioned above.
Also finished the week5 assignment as well as. 
Please check, thank you so much!

**Review by cwpeng — CHANGES_REQUESTED** [review]
Try to set sign in/up dialog style to display:none by default. Don't always show and hide it when page loading.

**Comment by viviweikuo** [comment]
@cwpeng 
Hi Teacher, I just want to inform you:
1. fixed up the sign-in/sign-up pop up problem
2. also finished the week 6 assignment's overall flow

However, there is a problem that I never succeed in paying the order.
Tappay server always sent me like: 

> {'status': 915, 'msg': 'System error, please contact TapPay customer service'}

I have checked my code and all flow about the payment issue together with teaching assistance, but still can not figure out what happened to this situation.
I will keep trying to solve this problem, but I think the overall flow was built actually.
So please check and inform me if there is any advice.

**Review by cwpeng — APPROVED** [review]
Your work is not good but acceptable. And you do not follow our work flow to submit task one by one per week, you just follow your own way to complete all the tasks. I have to remind you that it's not a way to do work in a team or in a company.

**Comment by viviweikuo** [comment]
Hi Teacher, I feel sorry about that I didn't notice the regulation carelessly, I will keep this in mind in the future. Also, thanks for your comments!

**Comment by cwpeng** [comment]
We have to merge pull request after review approval. And ask yourself why we have to do this.

**Pull request merged**
